apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mzci
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pfxd-tenant/rhtap-demo-app/hacbs-test-project-mzci@sha256:a347eb79eb0c6af5fe432e057b55a43b842a6e096ccf209d1bf8cb47c832bfdd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
